#!/usr/bin/env python

# INSTALLATION ################################################################
# Just drop into /etc/network/ifup.d
# Make sure it's marked as executable. (ie. chmod 755 ifup-lcdproc.py)
###############################################################################

import os
import sys
import time
from lcdproc.server import Server
import socket
import fcntl
import struct

def main(interface):
  if interface == 'lo': return
  if interface == '--all': return

  lcd = Server()
  lcd.start_session()

  s = lcd.add_screen("update")
  s.set_priority("alert")
  s.add_title_widget("title","Pulling..." % interface)
  os.chdir("/home/pi/Cacheberry-Pi")
  os.system("git pull")

  time.sleep(10)

if __name__=='__main__':
  if os.environ.has_key('IFACE'):
    iface = os.environ['IFACE']
    if os.fork() != 0: sys.exit()
    time.sleep(10)
    main(iface)
